[toolchain]
stdlib = "libstdc++"

[lock]
path = ".lito/lito.lock"

[patch."https://github.com/litocpp/rstd.git"]
path = "../deps/rstd"

[patch."https://github.com/litocpp/vvk.git"]
path = "../vvk"

[patch."https://github.com/hypengw/wavsen.git"]
path = "../wavsen"

[patch."https://github.com/hypengw/ncrequest.git"]
path = "../deps/ncrequest"

[patch."https://github.com/hypengw/QExtra.git"]
path = "../deps/QExtra"

[patch."https://github.com/hypengw/QmlMaterial.git"]
path = "../deps/qml_material"
